### ISSUE TITLE
识别准确率非常低

### ISSUE THREAD

**Issue by justein** [LeslieZhoa/tensorflow-facenet#2]
你好，非常感谢你将mtcnn和facenet做了整合，并附上了详细的注释。在使用的过程中发现，MTCNN经常检测出多个人脸（实际只有一个），我调整了min_face_size有所好转，但偶尔还是有这种情况出现；还有就是GPU模式下，mtcnn的detect face耗时很严重，能到1s以上偶尔，平均也要在700-800ms；最后就是判别的时候，正确率非常低，个人还是感觉这种单靠embeding的比较不太靠谱，请问你有什么好的办法么？

**Comment by LeslieZhoa** [comment]
Hi @justein 很高兴看到你的问题，首先MTCNN由于我当时在学校的时候训练服务器物理内存很小导致训练集并不是很大，训练次数也很小，所以可能精度有待提高。GPU耗时是把GPU启动时间加进去还是只是一次run的时间？是不是你的阈值设置过小，导致网络输入过大。对于facenet我也只是简单训练的几次迭代，所以精度还不是很高，你可以尝试调整匹配的阈值，看看结果有没有改观。如果你感觉embedding有问题，还可以尝试将embedding聚类或者求取距离来区分。
希望可以帮助到你！

**Comment by justein** [comment]
@LeslieZhoa 非常感谢你的解答！我打算将MTCNN重新训练一下。GPU耗时是取的run一次时间。我已经将阈值调整过了，现在要好很多。facenet这个也打算在GPU上重新训练一下， 有问题再交流，再次感谢！

**Comment by justein** [comment]
@LeslieZhoa 我在自己数据集上训练的，用的你提供的model迁移，跑了20个epoch，val上accuracy一直在87%左右，上不去，也下不来。

**Comment by LeslieZhoa** [comment]
Hi @justein 我分析原因有以下：
1.MTCNN训练还是有待提高
2.数据量少，原始数据和你自己的数据集分布不一致
3.我自己的facenet也没有训练太长时间，准确率也不是很高
希望对你有所帮助！

**Comment by justein** [comment]
@LeslieZhoa 感谢回复，感觉facenet的理论还是有点偏老了，近期打算研究下InsightFace。
